import { useState, useEffect } from "react";
import { supabase } from "../config/supabase";
import { isAutoGeneratedUsername } from "../utils/usernameCheck";

// Checks whether the currently logged-in user still has an
// auto-generated fallback username (e.g. "user_41859fe2"). If so,
// `needsSetup` becomes true so the app can show a prompt/modal asking
// them to choose a real one. Call `markComplete()` after a successful
// update to dismiss it for the rest of the session.
export default function useRequireUsernameSetup() {
  const [needsSetup, setNeedsSetup] = useState(false);
  const [checked, setChecked] = useState(false);

  useEffect(() => {
    const username = localStorage.getItem("username");
    if (!username) {
      setChecked(true);
      return;
    }

    if (isAutoGeneratedUsername(username)) {
      setNeedsSetup(true);
      setChecked(true);
      return;
    }

    setChecked(true);
  }, []);

  const markComplete = () => setNeedsSetup(false);

  return { needsSetup, checked, markComplete };
}