// Detects the fallback pattern your signup flow assigns when a user
// signs up (e.g. via Google OAuth) without picking a real username —
// e.g. "user_41859fe2". Adjust the regex if your generator uses a
// different prefix/format.
const AUTO_USERNAME_REGEX = /^user_[a-f0-9]{6,}$/i;

export const isAutoGeneratedUsername = (username) => {
  if (!username) return false;
  return AUTO_USERNAME_REGEX.test(username.trim());
};